services:
  postgres:
    image: postgres:16-alpine
    container_name: sih26102-postgres
    environment:
      POSTGRES_USER: sih26102
      POSTGRES_PASSWORD: sih26102pass
      POSTGRES_DB: sih26102_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


  ml-engine:
    build:
      context: .
      dockerfile: cloud-devops/docker/ml.Dockerfile
    ports:
      - "8080:8000"
    container_name: sih26102-ml-engine
    env_file:
      - .env  
  
  
  backend-case-management:
    build:
      context: .
      dockerfile: cloud-devops/docker/backend-case.Dockerfile
    ports:
      - "8002:8000"
    container_name: sih26102-backend-case-management
    env_file:
      - .env
    depends_on:
      - postgres


  frontend-dashboard:
    build:
      context: .
      dockerfile: cloud-devops/docker/frontend.Dockerfile
      args:
        - VITE_USE_MOCK=true
        - VITE_API_BASE_URL=http://localhost:8002 # Poornesh's case management port
    ports:
      - "3000:80"
    container_name: sih26102-frontend-dashboard

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend-case
    networks:
      - sih_network

   
  backend-data-api:
    build:
      context: .
      dockerfile: cloud-devops/docker/backend-data.Dockerfile
    ports:
      - "8001:8000"
    container_name: sih26102-backend-data-api

  volumes:
  postgres_data: