import RiskScoreRing from './RiskScoreRing';
import { recommendedAction, riskColorClasses } from '../utils/riskUtils';

export default function RiskExplanationPanel({ project }) {
  if (!project) return null;
  const { bg, text } = riskColorClasses(project.riskLevel);

  return (
    <div className="rounded-lg border border-border bg-surface shadow-card">
      <div className="flex items-center justify-between border-b border-border px-5 py-4">
        <div>
          <h3 className="font-display text-base font-semibold text-ink">Risk assessment</h3>
          <p className="text-xs text-muted">Generated by the anomaly / risk-scoring engine</p>
        </div>
        <RiskScoreRing score={project.riskScore} level={project.riskLevel} size={64} strokeWidth={6} />
      </div>

      <div className="space-y-4 px-5 py-4">
        <div>
          <p className="mb-2 text-xs font-semibold uppercase tracking-wide text-muted">Reasons</p>
          <ul className="space-y-2">
            {project.reasons.map((reason) => (
              <li key={reason.code} className="flex items-start gap-2 text-sm text-ink">
                <span className={`mt-1.5 h-1.5 w-1.5 flex-shrink-0 rounded-full ${text} bg-current`} />
                <span>{reason.text}</span>
              </li>
            ))}
          </ul>
        </div>

        <div className={`rounded ${bg} px-3 py-2.5`}>
          <p className={`text-xs font-semibold uppercase tracking-wide ${text}`}>Recommended action</p>
          <p className="mt-0.5 text-sm text-ink">{recommendedAction(project.riskLevel)}</p>
        </div>

        <p className="border-t border-border pt-3 text-xs leading-relaxed text-muted">
          A flagged project means it is worth a closer look - it is not a
          finding of guilt or confirmed wrongdoing. Final determination
          rests with the human reviewer.
        </p>
      </div>
    </div>
  );
}
// RiskExplanationPanel.jsx — owner: Chandana
