events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        # 1. Auth API (Poornesh)
        location /auth/ {
            proxy_pass http://backend-case-management:8000/auth/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 2. Case Management API (Poornesh)
        location /cases {
            proxy_pass http://backend-case-management:8000/cases;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /users {
            proxy_pass http://backend-case-management:8000/users;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/cases/ {
            proxy_pass http://backend-case-management:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 3. Data API (Mokshagna)
        location /works {
            proxy_pass http://backend-data-api:8000/api/v1/works;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /analytics/ {
            proxy_pass http://backend-data-api:8000/api/v1/analytics/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /anomalies/ {
            proxy_pass http://backend-data-api:8000/api/v1/anomalies/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/data/ {
            proxy_pass http://backend-data-api:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/v1/ {
            proxy_pass http://backend-data-api:8000/api/v1/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 4. ML Engine API (Kousic)
        location /api/ml/ {
            proxy_pass http://ml-engine:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 5. Frontend Dashboard (Chandana) - fallback
        location / {
            proxy_pass http://frontend-dashboard:80;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}