events {
    worker_connections 1024;
}

http {
    server {
        listen 80;

        # 1. Send all normal traffic to Chandana's React Frontend
        location / {
            proxy_pass http://frontend:3000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 2. Route Authentication & User requests to Poornesh's Auth API
        location /auth/ {
            proxy_pass http://backend-case:8002/auth/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 3. Route Case Management requests to Poornesh's Case API
        location /api/cases/ {
            proxy_pass http://backend-case:8002/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # 4. Route Data requests to Mokshagna's API (when ready)
        location /api/data/ {
            proxy_pass http://backend-data:8001/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Add ML Engine route in nginx/nginx.conf
        location /api/ml/ {
            proxy_pass http://ml-engine:8000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}